### ISSUE TITLE
Consider renaming the repository to "math-test-generator"

### ISSUE THREAD

**Issue by mgspross** [jalawelo/math-problem-generator#3]
I recommend changing the repository name to `math-test-generator` to better reflect the project's purpose and goals.

Presumably this would also become the name of the actual Python program we're developing (unless we can come up with better, catchier, and/or shorter name).

### Rationale

- I think the name `math-problem-generator` can be misconstrued to mean that the program we're developing generates a single math problem per run.

- The name `math-test-generator` better communicates the project's goal and what the program will actually do: generate and output a set of math problems to create math tests.

### Related Changes

If we rename the repository, we should also edit the `README.md` to reflect the new name.

**Comment by newoga** [comment]
My counter argument to this is that we're not actually generating a test, but a bank of problems that will be imported into a system that can be used for the purposes of creating tests. Most of the code will likely be designed in the context of a single problem, and some simple wrapper executable will likely execute that `n` number of times to create a bank. I'm fine with the name as is.

**Comment by mgspross** [comment]
Fair enough: let's keep the current name. I'm closing this issue.
